services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # REST API & Web UI
      - "6334:6334" # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage:z
    restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local
