version: "3.8"
services:
  mysql_db:
    image: mysql:latest
    container_name: MySQLCont
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql123
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql_db
    depends_on:
      - mysql_db

volumes:
  mysql_db:
    driver: local
