services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    restart: always
    ports:
      - 6379:6379
    command: ["valkey-server", "--requirepass", "valkey123"]
    volumes:
      - valkey-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:valkey:6379:0:valkey123
    ports:
      - 8091:8091
    depends_on:
      - valkey

volumes:
  valkey-data:
